name: Build with Gradle

on: [ push, pull_request ]

jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo and commit message doesn't start with [ci skip]
    if: >
      ${{
        (github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name)
        && ! startsWith(github.event.head_commit.message, '[ci skip]')
      }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: temurin
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew --no-daemon build
